import { logger } from "../shared/logger.js";
import { getMergeRequestNotes, getMergeRequestStatus, getProjectId } from "../shared/gitlab-api.js";
import { updateIncident } from "../shared/incident-store.js";
import type { Config } from "../shared/config.js";
import type Database from "better-sqlite3";

interface MrCommentState {
  mr_iid: number;
  last_note_id: number;
  last_checked: string;
}

/**
 * MR Comment Poller
 * 定期轮询所有 Spirit 创建的 MR，检测新评论并触发 handleMrReview
 */
export class MrCommentPoller {
  private config: Config;
  private db: Database.Database;
  private intervalMs: number;
  private timer: NodeJS.Timeout | null = null;
  private onNewComment: (incident_id: string, mr_iid: number) => Promise<void>;

  constructor(
    config: Config,
    db: Database.Database,
    intervalMs: number,
    onNewComment: (incident_id: string, mr_iid: number) => Promise<void>
  ) {
    this.config = config;
    this.db = db;
    this.intervalMs = intervalMs;
    this.onNewComment = onNewComment;
  }

  start() {
    logger.info(`MR Comment Poller starting (interval: ${this.intervalMs / 1000}s)`);
    this.poll(); // 立即执行一次
    this.timer = setInterval(() => this.poll(), this.intervalMs);
  }

  stop() {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
    logger.info("MR Comment Poller stopped");
  }

  private async poll() {
    try {
      // 查询所有状态为 resolved 且有 mr_iid 的 incidents
      const incidents = this.db
        .prepare(
          `SELECT id, mr_iid, branch, env, service
           FROM incidents
           WHERE status = 'resolved'
           AND mr_iid IS NOT NULL
           AND branch IS NOT NULL
           ORDER BY last_seen DESC
           LIMIT 50`
        )
        .all() as Array<{
          id: string;
          mr_iid: number;
          branch: string;
          env: string;
          service: string;
        }>;

      if (incidents.length === 0) {
        return;
      }

      logger.debug(`Checking ${incidents.length} MRs for new comments`);

      for (const incident of incidents) {
        await this.checkMrComments(incident);
      }
    } catch (err) {
      logger.error("MR Comment Poller error:", err);
    }
  }

  private async checkMrComments(incident: {
    id: string;
    mr_iid: number;
    branch: string;
    env: string;
    service: string;
  }) {
    try {
      // 找到对应的 code root
      const envConfig = this.config.environments.find((e) => e.name === incident.env);
      if (!envConfig) {
        return;
      }

      const codeRoot = envConfig.codeRoots.find((r) => r.name === incident.service) ?? envConfig.codeRoots[0];
      if (!codeRoot) {
        return;
      }

      // 获取 project ID
      const { getProjectId } = await import("../shared/gitlab-api.js");
      const projectId = await getProjectId(
        this.config.gitlab.url,
        this.config.gitlab.token,
        codeRoot.gitlabProjectPath
      );

      // 检查 MR 状态
      const mrStatus = await getMergeRequestStatus(
        this.config.gitlab.url,
        this.config.gitlab.token,
        projectId,
        incident.mr_iid
      );

      // 如果 MR 被 close，重新打开 incident
      if (mrStatus.state === "closed") {
        logger.info(`MR !${incident.mr_iid} was closed, reopening incident ${incident.id.slice(0, 8)}`);
        updateIncident(this.db, incident.id, {
          status: "open",
          mr_url: null,
          mr_iid: null,
          branch: null,
        });
        // 清理 MR 评论状态，以便下次重新处理
        this.db.prepare("DELETE FROM mr_comment_state WHERE mr_iid = ?").run(incident.mr_iid);
        return;
      }

      // 如果 MR 已合并，标记 incident 为 closed
      if (mrStatus.state === "merged") {
        logger.info(`MR !${incident.mr_iid} was merged, closing incident ${incident.id.slice(0, 8)}`);
        updateIncident(this.db, incident.id, { status: "closed" });
        return;
      }

      // 获取 MR 的所有评论
      const notes = await getMergeRequestNotes(
        this.config.gitlab.url,
        this.config.gitlab.token,
        projectId,
        incident.mr_iid
      );

      // 过滤人工评论（排除系统评论和机器人评论）
      const humanNotes = notes.filter(
        (n: any) =>
          !n.system &&
          n.body.trim().length > 0 &&
          !n.body.startsWith("## 🤖") &&
          !n.body.startsWith("## 🔧") &&
          !n.body.includes("Auto-generated by Spirit")
      );

      if (humanNotes.length === 0) {
        return;
      }

      // 获取最新评论
      const latestNote = humanNotes[humanNotes.length - 1];

      // 检查是否已经处理过这条评论
      const lastProcessed = this.getLastProcessedNoteId(incident.mr_iid);
      if (lastProcessed && latestNote.id <= lastProcessed) {
        return; // 已处理过
      }

      logger.info(
        `New comment detected on MR !${incident.mr_iid} from ${latestNote.author.username}: ${latestNote.body.slice(0, 100)}`
      );

      // 更新最后处理的评论 ID
      this.updateLastProcessedNoteId(incident.mr_iid, latestNote.id);

      // 触发回调处理评论
      await this.onNewComment(incident.id, incident.mr_iid);
    } catch (err) {
      logger.error(`Failed to check MR !${incident.mr_iid} comments:`, err);
    }
  }

  private getLastProcessedNoteId(mr_iid: number): number | null {
    try {
      const row = this.db
        .prepare("SELECT last_note_id FROM mr_comment_state WHERE mr_iid = ?")
        .get(mr_iid) as { last_note_id: number } | undefined;
      return row?.last_note_id ?? null;
    } catch {
      // 表可能不存在，创建它
      this.db.exec(`
        CREATE TABLE IF NOT EXISTS mr_comment_state (
          mr_iid INTEGER PRIMARY KEY,
          last_note_id INTEGER NOT NULL,
          last_checked TEXT NOT NULL
        )
      `);
      return null;
    }
  }

  private updateLastProcessedNoteId(mr_iid: number, note_id: number) {
    this.db
      .prepare(
        `INSERT OR REPLACE INTO mr_comment_state (mr_iid, last_note_id, last_checked)
         VALUES (?, ?, datetime('now'))`
      )
      .run(mr_iid, note_id);
  }
}
