#!/usr/bin/env tsx
/**
 * 测试 MR Comment Poller 功能
 * 用于验证评论检测和处理逻辑
 */
import { loadConfig } from "./shared/config.js";
import { initDb } from "./shared/incident-store.js";
import { getMergeRequestNotes, getProjectId } from "./shared/gitlab-api.js";
import { logger } from "./shared/logger.js";

async function testMrCommentPoller() {
  logger.info("=== Testing MR Comment Poller ===");

  const config = loadConfig();
  const db = initDb(config.storage.path);

  // 查询所有有 MR 的 incidents
  const incidents = db
    .prepare(
      `SELECT id, mr_iid, branch, env, service, title
       FROM incidents
       WHERE status = 'resolved'
       AND mr_iid IS NOT NULL
       ORDER BY last_seen DESC
       LIMIT 10`
    )
    .all() as Array<{
      id: string;
      mr_iid: number;
      branch: string;
      env: string;
      service: string;
      title: string;
    }>;

  if (incidents.length === 0) {
    logger.info("No incidents with MR found");
    return;
  }

  logger.info(`Found ${incidents.length} incidents with MRs`);

  for (const incident of incidents) {
    try {
      logger.info(`\n--- Incident ${incident.id.slice(0, 8)} ---`);
      logger.info(`Title: ${incident.title}`);
      logger.info(`MR: !${incident.mr_iid}`);
      logger.info(`Branch: ${incident.branch}`);
      logger.info(`Env/Service: ${incident.env}/${incident.service}`);

      // 找到对应的 code root
      const envConfig = config.environments.find((e) => e.name === incident.env);
      if (!envConfig) {
        logger.warn(`No environment config for ${incident.env}`);
        continue;
      }

      const codeRoot = envConfig.codeRoots.find((r) => r.name === incident.service) ?? envConfig.codeRoots[0];
      if (!codeRoot) {
        logger.warn(`No code root for service ${incident.service}`);
        continue;
      }

      // 获取 project ID
      const projectId = await getProjectId(
        config.gitlab.url,
        config.gitlab.token,
        codeRoot.gitlabProjectPath
      );

      // 获取 MR 评论
      const notes = await getMergeRequestNotes(
        config.gitlab.url,
        config.gitlab.token,
        projectId,
        incident.mr_iid
      );

      logger.info(`Total notes: ${notes.length}`);

      // 过滤人工评论
      const humanNotes = notes.filter(
        (n) =>
          !n.system &&
          n.body.trim().length > 0 &&
          !n.body.startsWith("## 🤖") &&
          !n.body.startsWith("## 🔧") &&
          !n.body.includes("Auto-generated by Spirit")
      );

      logger.info(`Human notes: ${humanNotes.length}`);

      if (humanNotes.length > 0) {
        logger.info("\nLatest human comments:");
        humanNotes.slice(-3).forEach((note, idx) => {
          logger.info(`\n[${idx + 1}] ${note.author.username} (${note.created_at}):`);
          logger.info(note.body.slice(0, 200) + (note.body.length > 200 ? "..." : ""));
        });

        // 检查 mr_comment_state 表
        try {
          const state = db
            .prepare("SELECT last_note_id, last_checked FROM mr_comment_state WHERE mr_iid = ?")
            .get(incident.mr_iid) as { last_note_id: number; last_checked: string } | undefined;

          if (state) {
            logger.info(`\nLast processed note ID: ${state.last_note_id}`);
            logger.info(`Last checked: ${state.last_checked}`);

            const latestNote = humanNotes[humanNotes.length - 1];
            if (latestNote.id > state.last_note_id) {
              logger.info(`✅ New comment detected! (${latestNote.id} > ${state.last_note_id})`);
              logger.info(`Would trigger handleMrReview for incident ${incident.id.slice(0, 8)}`);
            } else {
              logger.info(`No new comments (latest: ${latestNote.id}, processed: ${state.last_note_id})`);
            }
          } else {
            logger.info(`No state record found - first time processing this MR`);
            logger.info(`Would trigger handleMrReview for incident ${incident.id.slice(0, 8)}`);
          }
        } catch (err) {
          logger.warn(`mr_comment_state table not found (will be created on first run)`);
        }
      } else {
        logger.info("No human comments found");
      }
    } catch (err) {
      logger.error(`Failed to check MR !${incident.mr_iid}:`, err);
    }
  }

  db.close();
  logger.info("\n=== Test Complete ===");
}

testMrCommentPoller().catch((err) => {
  logger.error("Test failed:", err);
  process.exit(1);
});
